name: Build_Pull_Request

on:
  pull_request:
    branches:
      - main

jobs:
  Assemble:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Archive built jar
        uses: actions/upload-artifact@v3
        with:
          name: Built Jar
          path: build/libs/*.jar
